# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c11aa2a165127dde8df4ec0122e0926c30a0309edad212a945ad7b2627aa052a054548d9fbf4e4e319d2e87967e5ed8602a2fc5bf98479577c669542fd926030

test:
  secret_key_base: 12eb952ec340a72d60cae352d2f4141b6ff4b0bdf9f892b98063bf9834ab3ddd40c40bab1844c63184fed1498e840269f45f91a2a4a02c90abe59a09a2f4c3ab

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
